### ISSUE TITLE
能提供rss 订阅吗

### ISSUE THREAD

**Issue by changheluor007** [XuanwuAI/SectodayCommunity#2]
站点能提供rss 订阅吗，应该很多人都有这个需求

**Comment by yanzifan021** [comment]
+1

**Comment by ufofly** [comment]
不是一直都提供 rrs 订阅吗？https://xlab.tencent.com/cn/atom.xml

**Comment by yanzifan021** [comment]
> 不是一直都提供 rrs 订阅吗？https://xlab.tencent.com/cn/atom.xml

https://sectoday.tencent.com/info-today
https://xlab.tencent.com/cn/atom.xml

这应该是两个东西吧？内容都对不上

**Comment by A7um** [comment]
rss订阅我们正在规划中，后面会有的

**Comment by changheluor007** [comment]
> rss订阅我们正在规划中，后面会有的

坐等，等很久了，要不然每天看更新的内容还得自己转微信公众号rss ，太麻烦了

**Comment by WireFisher** [comment]
https://sectoday.tencent.com/api/atom.xml

Atom Feed 已经上线，内测中，欢迎大家试用~
目前的推送流还没有和微信公众号/新浪微博打通，等后续正式上线后，Atom Feed内容会保持和当天的公众号推送内容一致。

**Comment by changheluor007** [comment]
> https://sectoday.tencent.com/api/atom.xml
> 
> Atom Feed 已经上线，内测中，欢迎大家试用~ 目前的推送流还没有和微信公众号/新浪微博打通，等后续正式上线后，Atom Feed内容会保持和当天的公众号推送内容一致。

已添加

**Comment by changheluor007** [comment]
咦，这个上线的Atom Feed  是引流到别人的公众号那里吗

**Comment by WireFisher** [comment]
> 咦，这个上线的Atom Feed 是引流到别人的公众号那里吗

SectodayNext新增了一些来自微信公众号的数据源，所以确实会推一部分其他公众号的文章。理论上这些都是经过筛选后的高质量文章。如果对新版推送的内容有优化建议，请和我们分享，大家的意见非常宝贵！

**Comment by yanzifan021** [comment]
RSS 更新的周期是多少。今天7月24日，但是我刷rss还是7月23日的？能不能提供接口可供用户拉取最新的推送？如果有查询接口就更好了。 总之还是多谢大佬们了。；）

**Comment by liangjs** [comment]
RSS和首页文章目前已经改为同步更新了。

> RSS 更新的周期是多少。今天7月24日，但是我刷rss还是7月23日的？能不能提供接口可供用户拉取最新的推送？如果有查询接口就更好了。 总之还是多谢大佬们了。；）

**Comment by WireFisher** [comment]
> RSS 更新的周期是多少。今天7月24日，但是我刷rss还是7月23日的？能不能提供接口可供用户拉取最新的推送？如果有查询接口就更好了。 总之还是多谢大佬们了。；）

是否开发查询接口还得看后续规划，如果有消息会随时更新
